player={
  'name':'arum',
  'age':12,
  'alive':True,
  'fav_food':["🍕","🍔"],
  'friens':['a','b','c']
}
print(player)
print(player.get('age'))
print(player.get('fav_food'))
player.pop('age')
player['xp']=1500
print(player)
player['fav_food'].append("🍜")
print(player.get('fav_food'))